---
  config:
    monitor_ip: '192.168.64.39' #监控系统的vip(单节点部署模式则为主节点ip)
    monitor_url_port: 13402  #监控数据接口
    db_port: 5432 #数据库端口
    dates:
      date: '2021-03-09'    #默认为当日，也可手动指定日期，日期格式为xxxx-xx-xx，例如 2013-10-10
      s_time: 8   #开始时间，默认为早上8点，也可手动修改,但是必须为【0-23】之间的整数
      e_time: 20  #结束时间，默认为晚上8点，也可手动修改,但是必须为【0-23】之间的整数，切小于等于s_time
    hosts_black_sheet:        #默认为监控所有的云主机，如需要剔除的请在此按照yaml文件的如下格式输入云主机的ip，并取消注释
#      - 192.168.74.107

